VideoRentalApplication/Models/Customer.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoRentalApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Customer
    {
        public int custID { get; set; }

        [Required(ErrorMessage = "Customer Name is a required field")]
        [StringLength(15, ErrorMessage = "Customer Name cannot exceed more than 15 characters")]
        public string Name { get; set; }

        public bool IsSubscribedToNewsletter { get; set; }
        public int membershipTypeId { get; set; }

        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [MinAgeforMembership]  //Custom validation Attribute
        public Nullable<System.DateTime> BirthDate { get; set; }

        public virtual MembershipType MembershipType { get; set; }
    }
}

VideoRentalApplication/Controllers/Api/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;  // for MembershipType
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using VideoRentalApplication.Dto;
using VideoRentalApplication.Models;
using AutoMapper;

namespace VideoRentalApplication.Controllers.Api
{
    public class CustomersController : ApiController
    {
        private VideoRentalApplicationDBContext db;
        private CustomersController()
        {
            db = new VideoRentalApplicationDBContext();
            db.Configuration.ProxyCreationEnabled = false;
        }
        

        //Get Customers api/customers
        public IEnumerable<CustomerDto> getCustomers()
        {
            return db.Customers
                .Include(x => x.MembershipType)  // Eager Loading
                .ToList()
                .Select(Mapper.Map<Customer, CustomerDto>); 
        }

        // Get Customer by ID api/customers/1
        public CustomerDto getCustomerById(int id)
        {
            var customer = db.Customers.SingleOrDefault(x => x.custID == id);
            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);
            return Mapper.Map<Customer,CustomerDto>(customer);
        }

        // Post customer api/customers/
        [HttpPost]
        public CustomerDto createCustomer(CustomerDto customerDto)
        {
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);
            var customer = Mapper.Map<CustomerDto, Customer>(customerDto);
            db.Customers.Add(customer);
            db.SaveChanges();
            customerDto.custID = customer.custID;
            return customerDto;
        }

        // Put request api/customers/1
        [HttpPut]
        public void updateCustomer(int id, CustomerDto customerDto)
        {            
            if (!ModelState.IsValid)
                throw new HttpResponseException(HttpStatusCode.BadRequest);

            var customerInDB = db.Customers.SingleOrDefault(x => x.custID == id);
            if (customerInDB == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            Mapper.Map<CustomerDto, Customer>(customerDto, customerInDB);      
      
            /*customerInDB.Name = customer.Name;
            customerInDB.BirthDate = customer.BirthDate;
            customerInDB.MembershipType = customer.MembershipType;
            customerInDB.membershipTypeId = customer.membershipTypeId;
            customerInDB.IsSubscribedToNewsletter = customer.IsSubscribedToNewsletter;*/     
       
            db.SaveChanges();            
        }

        // delete customer api/customers/1
        [HttpDelete]
        public void deleteCustomer(int id)
        {
            var customer = db.Customers.SingleOrDefault(x => x.custID == id);
            if (customer == null)
                throw new HttpResponseException(HttpStatusCode.NotFound);

            db.Customers.Remove(customer);
            db.SaveChanges();            
        }
    }
}

VideoRentalApplication/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoRentalApplication.Models;
using VideoRentalApplication.ViewModels;

namespace VideoRentalApplication.Controllers
{
    public class CustomerController : Controller
    {
        private VideoRentalApplicationDBContext db = new VideoRentalApplicationDBContext();

        //
        // GET: /Customer/

        public ActionResult Index()
        {
            //var customers = db.Customers.Include(c => c.MembershipType);customers.ToList()
            return View();
        }
        public PartialViewResult Top3()  // Implementing Ajax
        {
            List<Customer> customers = db.Customers.OrderByDescending(x => x.Name).Take(3).ToList();
            return PartialView("_Customer", customers);
        }
        public PartialViewResult Bottom3()
        {
            List<Customer> customers = db.Customers.OrderBy(x => x.Name).Take(3).ToList();
            return PartialView("_Customer", customers);
        }

        //
        // GET: /Customer/Details/5

        public ActionResult Details(int custID)
        {
            Customer customer = db.Customers.SingleOrDefault(x => x.custID == custID);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }        

        //
        // GET: /Customer/Create

        public ActionResult Create()
        {
            Customer customer = new Customer();
            //ViewBag.membershipTypeId = new SelectList(db.MembershipTypes, "ID", "Name");
            var membershipType = db.MembershipTypes.ToList();
            var viewmodel = new CreateCustomerViewModel()   // Implementing View Model
            {
                Customer = customer,
                MembershipType = membershipType
            };
            return View(viewmodel);
        }

        //
        // POST: /Customer/Create

        [HttpPost]
        public ActionResult Create(CreateCustomerViewModel customerViewModel)
        {
            if (ModelState.IsValid)
            {
                db.Customers.Add(customerViewModel.Customer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.membershipTypeId = new SelectList(db.MembershipTypes, "ID", "Name", customerViewModel.Customer.membershipTypeId);
            return View("Create",customerViewModel);
        }

        //
        // GET: /Customer/Edit/5

        public ActionResult Edit(int custID)
        {
            Customer customer = db.Customers.Find(custID);
            if (customer == null)
            {
                return HttpNotFound();
            }
            ViewBag.membershipTypeId = new SelectList(db.MembershipTypes, "ID", "Name", customer.membershipTypeId);
            return View(customer);
        }

        //
        // POST: /Customer/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Customer customer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(customer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.membershipTypeId = new SelectList(db.MembershipTypes, "ID", "Name", customer.membershipTypeId);
            return View(customer);
        }

        //
        // GET: /Customer/Delete/5

        public ActionResult Delete(int custID = 0)
        {
            Customer customer = db.Customers.Find(custID);
            if (customer == null)
            {
                return HttpNotFound();
            }
            return View(customer);
        }

        //
        // POST: /Customer/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int custID)
        {
            Customer customer = db.Customers.Find(custID);
            db.Customers.Remove(customer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

VideoRentalApplication/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VideoRentalApplication.Models;

namespace VideoRentalApplication.Controllers
{
    public class MovieController : Controller
    {
        private VideoRentalApplicationDBContext db = new VideoRentalApplicationDBContext();

        //
        // GET: /Movie/

        public ActionResult Index()
        {
            //db.Movies.ToList()
            return View();
        }

        //
        // GET: /Movie/Details/5

        public ActionResult Details(int movieID)
        {
            Movie movie = db.Movies.SingleOrDefault(x => x.movieID == movieID);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        //
        // GET: /Movie/Create

        public ActionResult Create()
        {
            Movie movie = new Movie();
            return View(movie);
        }

        //
        // POST: /Movie/Create

        [HttpPost]
        public ActionResult Create(Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Movies.Add(movie);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(movie);
        }

        //
        // GET: /Movie/Edit/5

        public ActionResult Edit(int movieID)
        {
            Movie movie = db.Movies.SingleOrDefault(x => x.movieID == movieID);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        //
        // POST: /Movie/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Movie movie)
        {
            if (ModelState.IsValid)
            {
                db.Entry(movie).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(movie);
        }

        //
        // GET: /Movie/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Movie movie = db.Movies.Find(id);
            if (movie == null)
            {
                return HttpNotFound();
            }
            return View(movie);
        }

        //
        // POST: /Movie/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Movie movie = db.Movies.Find(id);
            db.Movies.Remove(movie);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

VideoRentalApplication/Views/Shared/_Customer.cshtml
@model IEnumerable<VideoRentalApplication.Models.Customer>

@Styles.Render("~/Content/bootstrapcss")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

<script src="~/Scripts/jquery-1.9.1.js"></script>
<script src="~/Scripts/jquery-1.9.1.min.js"></script>

<table>
    <tr>
       
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        
        
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        
    </tr>

@foreach (var item in Model) {
    <tr>
        
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
       
    </tr>
}

</table>

VideoRentalApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>Video Rental Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/bootstrapcss")
    @Styles.Render("~/Content/themes/base/css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")    
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-left">
                <nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("VideoRentalApp", "Index", "Home")</li>
                        <li>@Html.ActionLink("Customers", "Index", "Customer")</li>
                        <li>@Html.ActionLink("Movies", "Index", "Movie")</li>
                        <li>@Html.ActionLink("Location", "GetLocation", "Home")</li>
                        <li>@Html.ActionLink("Issue Tracker", "IssueTracker", "Home")</li>
                    </ul>
                </nav>
            </div>
            <div class="float-right">
                <section id="login">
                    @Html.Partial("_LoginPartial")
                </section>
                @*<nav>
                    <ul id="menu">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </nav>*@
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer>
        <div class="content-wrapper">
            <div class="float-left">
                <p>&copy; @DateTime.Now.Year - VideoRentalApplication Application</p>
            </div>
        </div>
    </footer>

    @Scripts.Render("~/bundles/lib")
    @RenderSection("scripts", required: false)
</body>
</html>